# PowerShell Script: Prepare Security Skills Assessment
# Purpose: Combine all skills.md files with assessment prompt for batch evaluation
# Platform: Windows (PowerShell 5.0+)
# Usage: .\prepare-skills-assessment.ps1

param(
    [string]$SkillsDir = "03_security skills files",
    [string]$PromptFile = "SECURITY_SKILLS_ASSESSMENT_PROMPT.md",
    [string]$OutputDir = "assessment-output"
)

# Colors for console output
$colors = @{
    Green   = "`e[32m"
    Yellow  = "`e[33m"
    Red     = "`e[31m"
    Blue    = "`e[34m"
    Reset   = "`e[0m"
}

Write-Host "$($colors.Blue)╔════════════════════════════════════════════════════════════╗$($colors.Reset)"
Write-Host "$($colors.Blue)║  Security Skills Assessment Preparation Script (Windows)      ║$($colors.Reset)"
Write-Host "$($colors.Blue)╚════════════════════════════════════════════════════════════╝$($colors.Reset)"
Write-Host ""

# Step 1: Validate prerequisites
Write-Host "$($colors.Yellow)📋 Step 1: Validating prerequisites...$($colors.Reset)"

if (-not (Test-Path $PromptFile)) {
    Write-Host "$($colors.Red)❌ ERROR: Assessment prompt file not found: $PromptFile$($colors.Reset)"
    Write-Host "   Please ensure SECURITY_SKILLS_ASSESSMENT_PROMPT.md is in the current directory."
    exit 1
}

if (-not (Test-Path $SkillsDir)) {
    Write-Host "$($colors.Red)❌ ERROR: Skills directory not found: $SkillsDir$($colors.Reset)"
    Write-Host "   Please ensure the skills directory path is correct."
    exit 1
}

Write-Host "$($colors.Green)✅ Prerequisites validated$($colors.Reset)"
Write-Host ""

# Step 2: Create output directory
Write-Host "$($colors.Yellow)📁 Step 2: Setting up output directory...$($colors.Reset)"

if (-not (Test-Path $OutputDir)) {
    New-Item -ItemType Directory -Path $OutputDir -Force | Out-Null
    Write-Host "$($colors.Green)✅ Created output directory: $OutputDir$($colors.Reset)"
} else {
    Write-Host "$($colors.Green)✅ Output directory exists: $OutputDir$($colors.Reset)"
}

Write-Host ""

# Step 3: Collect all skills.md files
Write-Host "$(@colors.Yellow)📂 Step 3: Collecting skills.md files...$($colors.Reset)"

$skillFiles = Get-ChildItem -Path $SkillsDir -Filter "*.md" -Recurse -Exclude "index.md" |
              Sort-Object FullName

if ($skillFiles.Count -eq 0) {
    Write-Host "$($colors.Red)❌ ERROR: No skills.md files found in $SkillsDir$($colors.Reset)"
    exit 1
}

Write-Host "$($colors.Green)✅ Found $($skillFiles.Count) skills.md files:$($colors.Reset)"
$skillFiles | ForEach-Object { Write-Host "   • $($_.FullName)" }
Write-Host ""

# Step 4: Create combined assessment input file
Write-Host "$($colors.Yellow)🔄 Step 4: Combining prompt + skills files...$($colors.Reset)"

$timestamp = Get-Date -Format "yyyy-MM-dd_HHmmss"
$outputFile = "$OutputDir\security-skills-assessment-input_$timestamp.md"

# Start with the prompt
$combinedContent = Get-Content $PromptFile -Raw

# Add separator
$combinedContent += "`n`n`n"
$combinedContent += "═" * 80
$combinedContent += "`n"
$combinedContent += "## SKILLS FILES TO ASSESS`n"
$combinedContent += "═" * 80
$combinedContent += "`n`n"

# Add each skills.md file
$fileCount = 0
$skillFiles | ForEach-Object {
    $fileCount++
    $relPath = Resolve-Path $_.FullName -Relative

    Write-Host "   [$fileCount/$($skillFiles.Count)] Adding: $relPath"

    $combinedContent += "`n`n"
    $combinedContent += "─" * 80
    $combinedContent += "`n"
    $combinedContent += "### File: $relPath`n"
    $combinedContent += "─" * 80
    $combinedContent += "`n`n"

    $combinedContent += Get-Content $_.FullName -Raw
    $combinedContent += "`n"
}

# Write combined file
Set-Content -Path $outputFile -Value $combinedContent -Encoding UTF8

Write-Host "$($colors.Green)✅ Combined file created: $outputFile$($colors.Reset)"
Write-Host "   Size: $((Get-Item $outputFile).Length / 1MB)MB"
Write-Host ""

# Step 5: Create additional helper files
Write-Host "$($colors.Yellow)📝 Step 5: Creating helper documentation...$($colors.Reset)"

# Create a README for the assessment
$readmeContent = @"
# Security Skills Assessment Package

## Files in this Package

1. **security-skills-assessment-input_[timestamp].md**
   - Combined prompt + all skills files
   - Ready to paste into Claude
   - Do not edit this file

2. **ASSESSMENT_INSTRUCTIONS.txt**
   - Step-by-step instructions for running the assessment
   - Contains copy-paste ready commands

## How to Use This Package

### Option A: Using Claude Web Chat (Recommended)
1. Open https://claude.ai
2. Create a new conversation
3. Copy the contents of: security-skills-assessment-input_[timestamp].md
4. Paste into the chat
5. Send the message
6. Claude will generate the assessment report
7. Copy the report and save to: security-skills-assessment-report_[timestamp].md

### Option B: Using Claude in VS Code
1. Open VS Code with Claude extension
2. Create a new Claude Chat window
3. Paste the combined input file contents
4. Send the message
5. Copy the report and save locally

### Option C: Using Claude Command Line (if available)
1. Copy the input file to your local machine
2. Use: claude < security-skills-assessment-input_[timestamp].md > report.md

## Important Notes

- The input file is large (multiple MB) — this is expected
- Claude will take 2-5 minutes to complete the assessment
- The report will be detailed and structured
- Save the report with a timestamp for tracking versions

## Next Steps After Assessment

1. Review the report for critical gaps
2. Assign ownership for gap remediation
3. Set timelines for each phase
4. Create issues/tickets for skill improvements
5. Schedule quarterly threat landscape reviews

## Questions?

If the assessment fails or produces unexpected results:
- Check that all skills files are properly formatted (.md)
- Ensure no binary files are in the skills directory
- Try with a smaller subset of files first
- Contact your security team lead

Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@

$readmeFile = "$OutputDir\README.txt"
Set-Content -Path $readmeFile -Value $readmeContent -Encoding UTF8
Write-Host "$($colors.Green)✅ Created: README.txt$($colors.Reset)"

# Create instructions file
$instructionsContent = @"
═══════════════════════════════════════════════════════════════════════════════
  SECURITY SKILLS ASSESSMENT — STEP-BY-STEP INSTRUCTIONS
═══════════════════════════════════════════════════════════════════════════════

WHAT YOU HAVE:
  • security-skills-assessment-input_[timestamp].md
    → This contains the assessment prompt + all your skills.md files combined
    → Ready to paste into Claude

STEP 1: OPEN CLAUDE
  → Go to https://claude.ai
  → OR open VS Code with Claude extension
  → OR use Claude in your IDE/editor of choice

STEP 2: COPY THE INPUT FILE
  → Open: security-skills-assessment-input_[timestamp].md
  → Select All (Ctrl+A or Cmd+A)
  → Copy (Ctrl+C or Cmd+C)

STEP 3: PASTE INTO CLAUDE
  → In a new Claude conversation, paste the entire contents
  → You should see the prompt followed by all your .md files

STEP 4: SEND TO CLAUDE
  → Type or paste this message alongside the input file:

  "Please assess these security skills.md files using the assessment rubric
   and output format provided above. Generate a comprehensive report with
   file-by-file analysis, domain-level summaries, and organizational gaps."

  → Click Send / Press Enter

STEP 5: WAIT FOR ASSESSMENT
  → Claude will process all files (takes 2-5 minutes)
  → You'll see a detailed report with:
    ✓ Individual file scores
    ✓ Strength/weakness analysis
    ✓ Critical gaps by domain
    ✓ Remediation roadmap

STEP 6: SAVE THE REPORT
  → Copy the report from Claude
  → Save it as: security-skills-assessment-report_[timestamp].md
  → Store in: assessment-output/ folder
  → Keep for audit trail & tracking changes

STEP 7: SHARE WITH TEAM
  → Share the report with security stakeholders
  → Discuss findings in your security review meeting
  → Assign ownership for gap remediation
  → Create tickets for updates

═══════════════════════════════════════════════════════════════════════════════

EXPECTED OUTPUT:

The report will include:
  • Executive summary (total files, average scores, gaps identified)
  • File-by-file analysis with 5 dimension scores (1-10 each)
  • Domain-level summaries (AI/LLM, Backend, DevOps, Frontend, Cross-cutting)
  • Critical organizational gaps with risk levels
  • Phase-based remediation roadmap
  • Next steps for governance & maintenance

═══════════════════════════════════════════════════════════════════════════════

TROUBLESHOOTING:

Q: File is too large to paste into Claude?
A: Break it into smaller parts:
   - Create separate assessments for each domain folder
   - Run: .\prepare-skills-assessment.ps1 -SkillsDir "03_security skills files/ai-engineer"

Q: Claude output is incomplete?
A: If the response is cut off, ask Claude to continue:
   "Please continue the assessment report from where you left off"

Q: Want to assess only one domain?
A: Edit the PowerShell script to filter by folder:
   $skillFiles = Get-ChildItem -Path "$SkillsDir\ai-engineer" -Filter "*.md" -Recurse

Q: Need to run this on a different PC?
A:
   1. Copy these 3 files to the other PC:
      • prepare-skills-assessment.ps1
      • SECURITY_SKILLS_ASSESSMENT_PROMPT.md
      • Your "03_security skills files" folder
   2. Run: .\prepare-skills-assessment.ps1
   3. Follow the instructions above

═══════════════════════════════════════════════════════════════════════════════

QUICK REFERENCE:

Command:           What it does:
─────────────────────────────────────────────────────────────────────────────
.\prepare-skills-  Generates combined input file with default settings
assessment.ps1

.\prepare-skills-  Generates input for only AI/LLM security skills
assessment.ps1 -SkillsDir "03_security skills files/ai-engineer"

.\prepare-skills-  Specifies custom output directory
assessment.ps1 -OutputDir "C:\assessments"

═══════════════════════════════════════════════════════════════════════════════

Generated: $(Get-Date -Format "yyyy-MM-dd HH:mm:ss")
"@

$instructionsFile = "$OutputDir\ASSESSMENT_INSTRUCTIONS.txt"
Set-Content -Path $instructionsFile -Value $instructionsContent -Encoding UTF8
Write-Host "$($colors.Green)✅ Created: ASSESSMENT_INSTRUCTIONS.txt$($colors.Reset)"

Write-Host ""

# Final summary
Write-Host "$($colors.Blue)╔════════════════════════════════════════════════════════════╗$($colors.Reset)"
Write-Host "$($colors.Blue)║  ✅ Assessment Package Ready!                              ║$($colors.Reset)"
Write-Host "$($colors.Blue)╚════════════════════════════════════════════════════════════╝$($colors.Reset)"
Write-Host ""
Write-Host "$($colors.Green)📦 Files created in: $OutputDir$($colors.Reset)"
Write-Host ""
Write-Host "Next steps:"
Write-Host "  1. Read: $OutputDir\README.txt"
Write-Host "  2. Follow: $OutputDir\ASSESSMENT_INSTRUCTIONS.txt"
Write-Host "  3. Copy contents of: $outputFile"
Write-Host "  4. Paste into Claude and run assessment"
Write-Host ""
Write-Host "Questions? Check ASSESSMENT_INSTRUCTIONS.txt for troubleshooting."
Write-Host ""
