@echo off
REM Batch Script: Prepare Security Skills Assessment
REM Purpose: Combine all skills.md files with assessment prompt for batch evaluation
REM Platform: Windows (Legacy - use PowerShell version if available)
REM Usage: prepare-skills-assessment.bat

setlocal enabledelayedexpansion

echo.
echo ============================================================================
echo   Security Skills Assessment Preparation Script (Windows Batch)
echo ============================================================================
echo.

REM Configuration
set SKILLS_DIR=03_security skills files
set PROMPT_FILE=SECURITY_SKILLS_ASSESSMENT_PROMPT.md
set OUTPUT_DIR=assessment-output
set TIMESTAMP=%date:~-4%%date:~-10,2%%date:~-7,2%_%time:~0,2%%time:~3,2%%time:~6,2%
set TIMESTAMP=%TIMESTAMP: =0%

REM Step 1: Validate prerequisites
echo [1/6] Validating prerequisites...

if not exist "%PROMPT_FILE%" (
    echo ERROR: Assessment prompt file not found: %PROMPT_FILE%
    echo Please ensure SECURITY_SKILLS_ASSESSMENT_PROMPT.md is in the current directory.
    pause
    exit /b 1
)

if not exist "%SKILLS_DIR%" (
    echo ERROR: Skills directory not found: %SKILLS_DIR%
    echo Please ensure the skills directory path is correct.
    pause
    exit /b 1
)

echo [OK] Prerequisites validated
echo.

REM Step 2: Create output directory
echo [2/6] Setting up output directory...

if not exist "%OUTPUT_DIR%" (
    mkdir "%OUTPUT_DIR%"
    echo [OK] Created output directory: %OUTPUT_DIR%
) else (
    echo [OK] Output directory exists: %OUTPUT_DIR%
)
echo.

REM Step 3: Create combined file
echo [3/6] Preparing combined assessment file...

set OUTPUT_FILE=%OUTPUT_DIR%\security-skills-assessment-input_%TIMESTAMP%.md

REM Copy the prompt file as the base
copy /Y "%PROMPT_FILE%" "%OUTPUT_FILE%" >nul

REM Append separator and skills files header
echo. >> "%OUTPUT_FILE%"
echo. >> "%OUTPUT_FILE%"
echo ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ >> "%OUTPUT_FILE%"
echo ## SKILLS FILES TO ASSESS >> "%OUTPUT_FILE%"
echo ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ >> "%OUTPUT_FILE%"
echo. >> "%OUTPUT_FILE%"

REM Count and append all .md files (excluding index.md)
setlocal enabledelayedexpansion
set FILE_COUNT=0

for /r "%SKILLS_DIR%" %%F in (*.md) do (
    if not "%%~nxF"=="index.md" (
        set /a FILE_COUNT+=1
        echo. >> "%OUTPUT_FILE%"
        echo. >> "%OUTPUT_FILE%"
        echo ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ >> "%OUTPUT_FILE%"
        echo ### File: %%F >> "%OUTPUT_FILE%"
        echo ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ >> "%OUTPUT_FILE%"
        echo. >> "%OUTPUT_FILE%"

        type "%%F" >> "%OUTPUT_FILE%"
        echo. >> "%OUTPUT_FILE%"

        echo    [!FILE_COUNT!] Added: %%F
    )
)

echo [OK] Combined file created: %OUTPUT_FILE%
echo [OK] Total skills files processed: %FILE_COUNT%
echo.

REM Step 4: Create README
echo [4/6] Creating documentation...

(
    echo # Security Skills Assessment Package
    echo.
    echo ## Files in this Package
    echo.
    echo 1. **security-skills-assessment-input_%TIMESTAMP%.md**
    echo    - Combined prompt + all skills files
    echo    - Ready to paste into Claude
    echo    - Do not edit this file
    echo.
    echo 2. **ASSESSMENT_INSTRUCTIONS.txt**
    echo    - Step-by-step instructions for running the assessment
    echo    - Contains copy-paste ready commands
    echo.
    echo ## How to Use
    echo.
    echo 1. Open the combined input file: security-skills-assessment-input_%TIMESTAMP%.md
    echo 2. Copy all contents (Ctrl+A, Ctrl+C)
    echo 3. Go to https://claude.ai and create a new conversation
    echo 4. Paste the contents into Claude
    echo 5. Ask: "Please assess these security skills.md files using the rubric provided"
    echo 6. Wait for Claude to generate the assessment report (2-5 minutes)
    echo 7. Copy the report and save it locally
    echo.
    echo For detailed instructions, see: ASSESSMENT_INSTRUCTIONS.txt
    echo.
    echo Generated: %date% %time%
) > "%OUTPUT_DIR%\README.txt"

echo [OK] Created: %OUTPUT_DIR%\README.txt
echo.

REM Step 5: Create instructions
echo [5/6] Creating step-by-step instructions...

(
    echo ============================================================================
    echo   SECURITY SKILLS ASSESSMENT - INSTRUCTIONS
    echo ============================================================================
    echo.
    echo WHAT YOU HAVE:
    echo   - security-skills-assessment-input_%TIMESTAMP%.md
    echo     Contains: Assessment prompt + all %FILE_COUNT% skills.md files combined
    echo.
    echo STEP 1: COPY THE COMBINED FILE
    echo   - Open: security-skills-assessment-input_%TIMESTAMP%.md
    echo   - Press Ctrl+A to select all
    echo   - Press Ctrl+C to copy
    echo.
    echo STEP 2: OPEN CLAUDE
    echo   - Go to https://claude.ai
    echo   - OR open VS Code with Claude extension
    echo.
    echo STEP 3: PASTE INTO CLAUDE
    echo   - Create new conversation
    echo   - Paste the entire file contents (Ctrl+V)
    echo.
    echo STEP 4: SEND TO CLAUDE
    echo   Type this message:
    echo   "Please assess these security skills.md files using the assessment
    echo    rubric and output format provided. Generate a comprehensive report."
    echo.
    echo STEP 5: WAIT FOR ASSESSMENT
    echo   - Claude will process all files (takes 2-5 minutes)
    echo   - You'll receive a detailed report with:
    echo     * File-by-file analysis
    echo     * Domain-level summaries
    echo     * Organizational gaps
    echo     * Remediation roadmap
    echo.
    echo STEP 6: SAVE THE REPORT
    echo   - Copy the report from Claude
    echo   - Save as: security-skills-assessment-report_[timestamp].md
    echo   - Store in: assessment-output folder
    echo.
    echo STEP 7: SHARE WITH TEAM
    echo   - Present findings to security stakeholders
    echo   - Assign ownership for gap remediation
    echo   - Create tickets for improvements
    echo.
    echo ============================================================================
    echo TROUBLESHOOTING
    echo ============================================================================
    echo.
    echo File too large?
    echo   - Break into smaller batches by domain
    echo   - Edit script to point to specific subfolder
    echo.
    echo Claude cuts off the response?
    echo   - Ask: "Please continue the report from where you left off"
    echo.
    echo Transferring to another PC?
    echo   - Copy these files:
    echo     1. prepare-skills-assessment.ps1 OR prepare-skills-assessment.bat
    echo     2. SECURITY_SKILLS_ASSESSMENT_PROMPT.md
    echo     3. Your 03_security_skills_files folder
    echo   - Run the script on the other PC
    echo.
    echo ============================================================================
    echo Generated: %date% %time%
) > "%OUTPUT_DIR%\ASSESSMENT_INSTRUCTIONS.txt"

echo [OK] Created: ASSESSMENT_INSTRUCTIONS.txt
echo.

REM Step 6: Summary
echo [6/6] Summary
echo.
echo ============================================================================
echo   ASSESSMENT PACKAGE READY!
echo ============================================================================
echo.
echo Location: %OUTPUT_DIR%
echo.
echo Files created:
echo   - security-skills-assessment-input_%TIMESTAMP%.md
echo   - README.txt
echo   - ASSESSMENT_INSTRUCTIONS.txt
echo.
echo Next steps:
echo   1. Read: %OUTPUT_DIR%\ASSESSMENT_INSTRUCTIONS.txt
echo   2. Copy contents: security-skills-assessment-input_%TIMESTAMP%.md
echo   3. Paste into Claude at: https://claude.ai
echo   4. Request assessment
echo   5. Save the report
echo.
echo ============================================================================
echo.
pause
